from .dark_templar_rush import DarkTemplarRush
from .proxy_zealot_rush import ProxyZealotRushBot
from .macro_stalkers import MacroStalkers
from .gate4 import Stalkers4Gate
from .robo import MacroRobo
from .voidray import MacroVoidray
from .cannon_rush import CannonRush
from .adept_allin import AdeptRush
from .protoss_random import RandomProtossBot
from .disruptor import SharpSphereBot
from .one_base_tempests import OneBaseTempests
